### ISSUE TITLE
Custom handler for error JSON

### ISSUE THREAD

**Issue by linjunpop** [asaaki/ralitobu_plug#2]
Is that possible to allow custom handler when exceed limit. Maybe something like `plug Guardian.Plug.EnsureAuthenticated, handler: MyApp.MyAuthErrorHandler`.

So, the error JSON can be customized as needed. :)

**Comment by asaaki** [comment]
Ill think about it, at least sounds like a nice feature.
But also feel free to propose something if you already have an idea.

**Comment by asaaki** [comment]
No active development.
